<?php
namespace Merlin\Mvc;

use Merlin\AppContext;
use Merlin\Http\Cookies;
use Merlin\Http\Request;
use Merlin\Http\Session;
use Merlin\Http\Response;

/**
 * MVC Controller class
 */
abstract class Controller
{
	/**
	 * Controller-wide middleware
	 * Example:
	 * protected array $middleware = [
	 *     AuthMiddleware::class,
	 *     [RoleMiddleware::class, ['admin']],
	 * ];
	 */
	protected array $middleware = [];

	/**
	 * Action-specific middleware
	 * Example:
	 * protected array $actionMiddleware = [
	 *     'editAction' => [
	 *         AuthMiddleware::class,
	 *         [RoleMiddleware::class, ['admin']],
	 *     ],
	 * ];
	 */
	protected array $actionMiddleware = [];

	// --- Lifecycle hooks ---

	/**
	 * Optional method to run before an action. If it returns a Response, the action will be skipped and the response sent immediately.
	 * @param string $action The name of the action being executed (e.g. "editAction")
	 * @param array $params The parameters passed to the action (e.g. route variables or DI-resolved dependencies)
	 * @return Response|null If a Response is returned, it will be sent immediately and the action will be skipped. If null is returned, the action will execute as normal.
	 */
	public function beforeAction(string $action = null, array $params = []): ?Response
	{
		return null;
	}

	/**
	 * Optional method to run after an action. It receives the Response returned by the action (or generated by the framework if the action returned something else). If it returns a Response, that response will be sent instead of the original one.
	 * @param string $action The name of the action that was executed (e.g. "editAction")
	 * @param array $params The parameters passed to the action (e.g. route variables or DI-resolved dependencies)
	 * @return Response|null If a Response is returned, it will replace the original response from the action. If null is returned, the original response will be sent.
	 */
	public function afterAction(string $action = null, array $params = []): ?Response
	{
		return null;
	}

	// --- Middleware getters ---

	/**
	 * Get the middleware for the controller. Usually used by the Dispatcher to build the middleware pipeline for the current request.
	 * @return array
	 */
	public function getMiddleware(): array
	{
		return $this->middleware;
	}

	/**
	 * Get the middleware for a specific action. Usually used by the Dispatcher to build the middleware pipeline for the current request.
	 * @param string $action The name of the action (e.g. "editAction")
	 * @return array
	 */
	public function getActionMiddleware(string $action): array
	{
		return $this->actionMiddleware[$action] ?? [];
	}

	// --- Helpers ---

	/**
	 * Get the current AppContext instance. Useful for accessing services or route info from the controller.
	 * @return AppContext
	 */
	public function context(): AppContext
	{
		return AppContext::instance();
	}

	/**
	 * Get the current Request object from the context.
	 * @return Request
	 */
	public function request(): Request
	{
		return $this->context()->request();
	}

	/**
	 * Get the ViewEngine from the context for rendering views.
	 * @return ViewEngine
	 */
	public function view(): ViewEngine
	{
		return $this->context()->view();
	}

	/**
	 * Get the Session from the context. May return null if no session is available.
	 * @return Session|null
	 */
	public function session(): ?Session
	{
		return $this->context()->session();
	}

	/**
	 * Get the Cookies service from the context for managing cookies.
	 * @return Cookies
	 */
	public function cookies(): Cookies
	{
		return $this->context()->cookies();
	}
}
